### ISSUE TITLE
Webhook support

### ISSUE THREAD

**Issue by mphacker** [SaviorXTanren/StreamingClientLibrary#76]
Just curious about thoughts around adding webhook support into the library, or maybe as a separate optional library.  Features such as near real-time stream change (online/offline/etc...), follower notification, and Hype Train events could be very useful to a bot.  The other options are to do polling of both the channel, follower, and hype train APIs which works but provides delayed data.

Since webhook would require an inbound connection this does complicate things since most systems running bots are behind NAT / Firewall devices.   UPnP could possibly be used to overcome that issue and make running a bot using such a solution easier.

I am just sure how complicated it would be to implement such a feature as I haven't really tried to implement a webhook receiver within a library.

**Comment by SaviorXTanren** [comment]
I personally have no use for web hooks support right now, but it was something on the back of my mind to add at some point. Right now, anything I need via web hooks I do with 1 minute interval polling, which isn't horribly unreasonable. I'm not going to set anything up to have web hooks run locally on a person's machine, that's opening up a can of worms that I don't want to put on anyone without the highest amount of network security knowledge; especially given the sorts of network attacks that occur in the streaming world.

From a development perspective, it's not going to be hard to do because it's just going to be the processing logic & models for the web hook events. Everything else around the actual standing up of the API service would be on the end-user.

**Comment by mphacker** [comment]
Understood and agree 100% about the network security concerns.
