### ISSUE TITLE
YouTube current Nuget broken

### ISSUE THREAD

**Issue by Bappsack** [SaviorXTanren/StreamingClientLibrary#79]
the current nuget package doesnt work with the latest Google.API, have to build manually and added as refference.

**Comment by SaviorXTanren** [comment]
I don't really understand what the issue is? Nuget packages are only set up to work against the specific version that they're referencing. If you have a newer version of a dependent library, it's not necessarily going to link against automatically.

You'll need to explain more what it is you're looking for exactly. Are you just asking me to update the library to the latest version?

**Comment by Bappsack** [comment]
> I don't really understand what the issue is? Nuget packages are only set up to work against the specific version that they're referencing. If you have a newer version of a dependent library, it's not necessarily going to link against automatically.
> 
> You'll need to explain more what it is you're looking for exactly. Are you just asking me to update the library to the latest version?

Currently if you want to use the current nuget assembly with the dependent libs it fails to fetch the LiveStream and user method (can't give proper Details right now since i'm at work).

Master works fine so updating the nuget should be fine for now.

**Comment by SaviorXTanren** [comment]
Yea, that's just a problem with using two different versions of the same package. I'm not necessarily going to update the nuget package every time YouTube releases a new update to their nuget packages, that's just impractical to do. Updates to our nuget packages will coincide with code changes on our end or large updates to dependencies.

So if you want to use the nuget package version of this library, you'll need to keep your references in your main project to the same version. Otherwise you'll need to simply pull down the library code directly and update it to make the version you're using.
