### ISSUE TITLE
Twitch Schedule API

### ISSUE THREAD

**Issue by mphacker** [SaviorXTanren/StreamingClientLibrary#87]
Looks like Twitch decided to break with it's prior JSON results structure with the Get Channel Stream Schedule API.  Instead of having the paged results under data, they have it under segments.  This makes the existing base code used for getting paged results no longer work.   Any thoughts on how best to deal with this situation without having to create one-off paged results methods for situations like this?

https://dev.twitch.tv/docs/api/reference#get-channel-stream-schedule

**Comment by SaviorXTanren** [comment]
It doesn't really change much, we would just expose another type of class who's data property is an object instead of a list then re-adjust the paged logic just take a function that handle the actual de-serializing of the data.. That said, the Twitch Schedule API is pretty low on the priority as far as usage, so not something I plan on tackling any time soon.
