### ISSUE TITLE
EventSub objects

### ISSUE THREAD

**Issue by mphacker** [SaviorXTanren/StreamingClientLibrary#88]
The Twitch EventSub notification JSON objects do not seem to match the objects returned from the APIs.  Does it make sense to create a series of EventSub models to make working with the data easier or do you prefer to keep that out of the library?

**Comment by SaviorXTanren** [comment]
I'm not sure what you mean by them not matching the objects? The models match up with the **APIs** that are used for EventSub:

https://dev.twitch.tv/docs/api/webhooks-reference/#subscribe-tounsubscribe-from-events
https://dev.twitch.tv/docs/api/reference/#get-webhook-subscriptions

But those are different than the actual packets sent to the callback webbook. Each of them is the same base packet, but the type inside it is different. So it doesn't make sense to dedicated models for each because they're not unique in that way. Most are also very similar to models that are returned from similar API calls.
